### ISSUE TITLE
Can't redirect to the result page after login user

### ISSUE THREAD

**Issue by belcon** [lepture/example-oauth2-server#10]
Here is what I do:
1. Directly create all necessary data into sqlite database.
2. Access https://127.0.0.1:8000/
    Redirect the browser to https://127.0.0.1:5000/. Require input user name. I input user name. But the page shows the user name that I input to me. What I expects is that the page of '/api/me'.
3. But if I visit https://127.0.0.1:8000/ again, I will get the page of '/api/me'.

Can this example act just like the other providers such as reddit.com?
First access one page, then input user name (and password perhaps), finally come out the result. (Suppose all data needed is already in the database)

**Comment by octavioturra** [comment]
+1

**Comment by lepture** [comment]
Follow the console log. One should be `localhost` instead of `127.0.0.1`.

**Comment by vl4dt** [comment]
+1

**Comment by lepture** [comment]
Please follow the console log. You should visit one as `localhost` instead of `127.0.0.1`
