### ISSUE TITLE
Document how to use

### ISSUE THREAD

**Issue by probonopd** [lepture/example-oauth2-server#26]
I have read the blog post, but it describes more in which steps the example-oauth2-server was made rather than how to use it.

I am trying to set up an OAuth2 server which clients can authenticate against.

I have installed example-oauth2-server on my server, now what?

I get "You are not authenticated, Type any username" and no matter what username I type I am always redirected to /.

I would have expected to be able to generate JWT tokens, can I do that?

**Comment by sholsapp** [comment]
+1 this would be useful.

**Comment by lepture** [comment]
> Now it is time for testing. We would create a client.py to do the job. Here is a little trick:

> And now start the server and client and visit `http://localhost:8000/`. You will finally get an access token.

**Comment by EvanBurbidge** [comment]
Quick question how would I go about defining my own server, I can see examples on how to create tokens from FB, Twitter etc. But how would you go about getting one for users on your front end trying to access the web api on your backend?

**Comment by KleinYuan** [comment]
Also have this prob
When I run the app.py and client.py. The app runs fine but I cannot visit the client page ("The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.")
I realized that it seems that the authorize.html is never rendered.
Newbie to OAuth2.
Anyone met same problem?

**Comment by KleinYuan** [comment]
Hi lepture,
Somehow the client does not work for me.
When I visit the http://localhost:8000/, it will actually directly jump to http://127.0.0.1:5000/oauth/errors?error=invalid_request&error_description=Mismatching+redirect+URI.

showing:

Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.


Do you know why?

**Comment by indera** [comment]
@see https://github.com/lepture/example-oauth2-server/pull/27
