### ISSUE TITLE
Issues with the /authorize api

### ISSUE THREAD

**Issue by Chitrank-Dixit** [lepture/example-oauth2-server#31]
Well , this is very nice example to get me going with oauth in flask otherwise need to hardcode a lot. I am stuck at /authorize api here. I have read Usage section and I am able to successfully implement this , but as I am using restful apis , I need to expose this to the front end and therefore I have separated the apis. Now I need to know in Usage step # 6. In /authorize api

The API is like /authorize?code=<some_code>,  This is the code But I am unable to figure out what code is actually the value of this code, To do this I need to send this code value to the front end so that it can get the access_token with that.

**Comment by lepture** [comment]
`/authorize?code=<some_code>` this is the client part, not the server part.
