### ISSUE TITLE
TypeError: sequence index must be integer, not 'str'

### ISSUE THREAD

**Issue by sarthakdev90** [lepture/example-oauth2-server#4]
![screenshot from 2014-01-30 14 18 53](https://f.cloud.github.com/assets/6458186/2038331/21468d06-898c-11e3-8c0e-3837659b4668.png)

**Comment by Kareeeeem** [comment]
I am still having this issue. Even when I install oauthlib 0.6.0.

**Comment by ashish-arora02** [comment]
I have found this issue, it is due to the "Post" method not allowed to access_token function in app.py file. It is working at my end now. Here is the code diff https://github.com/ashish-arora02/example-oauth2-server/commit/5f8658e1316c9d615994629d525cf5e87f48b9ab
